### ISSUE TITLE
Missing API features?

### ISSUE THREAD

**Issue by itomek** [dustyhoppe/fantasydata-client-net#3]
Is the current API up to date? I'm missing things like "Get Schedules for Season" (or am i missing something)? Are there plans to include that?

**Comment by hopdizzle** [comment]
itomek, you are correct. The api wrapper in not currently up to date. I'm currently adding support for  "Get Schedule for Season" on the NFL api. You will be able to see it in the 1.0.7.1 nuget release when I push that out.
